# Generated by Django 6.1 on 2026-08-21 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('country_of_residence', models.CharField(blank=True, max_length=100)),
                ('preferred_destination', models.CharField(blank=True, choices=[('uk', 'United Kingdom'), ('usa', 'USA'), ('canada', 'Canada'), ('australia', 'Australia'), ('malaysia', 'Malaysia'), ('other', 'Other')], max_length=20)),
                ('interested_service', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('website', 'Website Form'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('referral', 'Referral'), ('walk_in', 'Walk-in'), ('other', 'Other')], default='website', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('consultation_booked', 'Consultation Booked'), ('application_started', 'Application Started'), ('visa_processing', 'Visa Processing'), ('won', 'Won — Enrolled'), ('lost', 'Lost')], default='new', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('mode', models.CharField(choices=[('phone', 'Phone'), ('video', 'Video'), ('in_person', 'In person')], default='phone', max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='leads.lead')),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
