# Generated by Django 6.1 on 2026-09-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='country_of_residence',
        ),
        migrations.AddField(
            model_name='lead',
            name='future_plan',
            field=models.TextField(blank=True, help_text='What the student hopes to do after this programme'),
        ),
        migrations.AddField(
            model_name='lead',
            name='programme',
            field=models.CharField(blank=True, help_text="e.g. Bachelor's, Master's, Foundation", max_length=150),
        ),
        migrations.AddField(
            model_name='lead',
            name='subject',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='lead',
            name='university',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
