# Generated by Django 6.1 on 2026-08-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('study_abroad', 'Study Abroad'), ('visa', 'Visa Support'), ('scholarship', 'Scholarship')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_bn', models.CharField(max_length=200, null=True)),
                ('title_ar', models.CharField(max_length=200, null=True)),
                ('title_ur', models.CharField(max_length=200, null=True)),
                ('title_fa', models.CharField(max_length=200, null=True)),
                ('title_ms', models.CharField(max_length=200, null=True)),
                ('title_fr', models.CharField(max_length=200, null=True)),
                ('title_ru', models.CharField(max_length=200, null=True)),
                ('title_zh_hans', models.CharField(max_length=200, null=True)),
                ('title_es', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.CharField(max_length=300)),
                ('summary_en', models.CharField(max_length=300, null=True)),
                ('summary_bn', models.CharField(max_length=300, null=True)),
                ('summary_ar', models.CharField(max_length=300, null=True)),
                ('summary_ur', models.CharField(max_length=300, null=True)),
                ('summary_fa', models.CharField(max_length=300, null=True)),
                ('summary_ms', models.CharField(max_length=300, null=True)),
                ('summary_fr', models.CharField(max_length=300, null=True)),
                ('summary_ru', models.CharField(max_length=300, null=True)),
                ('summary_zh_hans', models.CharField(max_length=300, null=True)),
                ('summary_es', models.CharField(max_length=300, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_bn', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('description_ur', models.TextField(null=True)),
                ('description_fa', models.TextField(null=True)),
                ('description_ms', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_zh_hans', models.TextField(null=True)),
                ('description_es', models.TextField(null=True)),
                ('icon', models.CharField(blank=True, help_text='e.g. bootstrap icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
