# Generated by Django 6.1 on 2026-08-21 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_en', models.CharField(max_length=100, null=True, unique=True)),
                ('name_bn', models.CharField(max_length=100, null=True, unique=True)),
                ('name_ar', models.CharField(max_length=100, null=True, unique=True)),
                ('name_ur', models.CharField(max_length=100, null=True, unique=True)),
                ('name_fa', models.CharField(max_length=100, null=True, unique=True)),
                ('name_ms', models.CharField(max_length=100, null=True, unique=True)),
                ('name_fr', models.CharField(max_length=100, null=True, unique=True)),
                ('name_ru', models.CharField(max_length=100, null=True, unique=True)),
                ('name_zh_hans', models.CharField(max_length=100, null=True, unique=True)),
                ('name_es', models.CharField(max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('flag_emoji', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('city', models.CharField(max_length=100)),
                ('ranking', models.PositiveIntegerField(blank=True, null=True)),
                ('tuition_from_usd', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_bn', models.TextField(blank=True, null=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('description_ur', models.TextField(blank=True, null=True)),
                ('description_fa', models.TextField(blank=True, null=True)),
                ('description_ms', models.TextField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_zh_hans', models.TextField(blank=True, null=True)),
                ('description_es', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='universities/logos/')),
                ('is_featured', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='universities.country')),
            ],
            options={
                'ordering': ['ranking', 'name'],
            },
        ),
    ]
